<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FarolOrbital</RootNamespace>
    <AssemblyName>FarolOrbital</AssemblyName>
  </PropertyGroup>

  <!-- Copia o JSON mockado para o diretório de saída junto com o executável -->
  <ItemGroup>
    <Content Include="Data/dados_orbitais_mock.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
